#ifndef __COMMON_NN_WRAPPER__
#define __COMMON_NN_WRAPPER__

#define MAX(x,y) (x)>(y) ? (x):(y)

#define TEMPLATE template<typename T> 
enum POOLING_TYPE {MAX_POOL,AVG_POOL};
enum LAYER_TYPES {INPUT_LAYER,POOLING_LAYER,CONVOLUTION_LAYER,FLATTEN_LAYER};
enum ACTIVATION_TYPES {TANH,SIGMOID,RELU,LEAKY_RELU,LINEAR};

#endif